YSMOD-143
navikt/yrkesskade-skadeforklaring-api pull request #1
Opened 2022-04-19 06:04 UTC by lurajon

- ny virusskanner funksjonalitet
- åpnet for clamav i nais konfigurasjonen
- la til kodeverk i wiremock konfigurasjon
- utvidet tester

2022-04-19 14:37 UTC, olsnerik requested changes
Mye fint :)

2022-04-19 14:37 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/skadeforklaring/integration/virusskanner/VirusScannerClient.kt
> +            .baseUrl(virusScannerConfig.toString())
Hmm, synes denne så rar ut jeg, hentes urlen ut med selve configen sin toString altså?

2022-04-19 14:37 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/skadeforklaring/integration/virusskanner/VirusScannerClient.kt
> +        val scanResults = client.put().uri("").body(Mono.just(data), ByteArray::class.java).retrieve().bodyToMono<Array<ScanResult>>().block().orEmpty()
hva gjør uri("") ?

2022-04-19 14:37 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/skadeforklaring/mockserver/AbstractMockServer.kt
>  open class AbstractMockSever(private val port: Int?) {
Gjerne rename denne til AbstractMockServer selv om dette ikke er endret nå

2022-04-20 05:14 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/skadeforklaring/integration/virusskanner/VirusScannerClient.kt
> +            .baseUrl(virusScannerConfig.toString())
Bra sett!! Jeg hadde glemt å endre fra gammel kode som kun var URI, til config.url

2022-04-20 05:14 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/skadeforklaring/integration/virusskanner/VirusScannerClient.kt
> +        val scanResults = client.put().uri("").body(Mono.just(data), ByteArray::class.java).retrieve().bodyToMono<Array<ScanResult>>().block().orEmpty()
Ingenting. Jeg fjerner den

2022-04-20 05:14 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/skadeforklaring/mockserver/AbstractMockServer.kt
>  open class AbstractMockSever(private val port: Int?) {
Fikset!

2022-04-20 07:17 UTC, olsnerik approved these changes

2022-04-20 07:20 UTC, merged